/**
 * Crof.AI Custom Provider
 *
 * OpenAI-compatible provider with base URL https://crof.ai/v1
 * Models and pricing sourced from https://crof.ai/pricing
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  pi.registerProvider("crof-ai", {
    name: "Crof.AI",
    baseUrl: "https://crof.ai/v1",
    apiKey: "$CROF_AI_API_KEY",
    api: "openai-completions",
    models: [
      // ── DeepSeek Models ──────────────────────────────────────────────
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.35, output: 0.8, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true, thinkingFormat: "deepseek" },
      },
      {
        id: "deepseek-v4-pro-lightning",
        name: "DeepSeek V4 Pro (Lightning)",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.8, output: 1.6, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true, thinkingFormat: "deepseek" },
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.12, output: 0.21, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true, thinkingFormat: "deepseek" },
      },
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.18, output: 0.35, cacheRead: 0.04, cacheWrite: 0 },
        contextWindow: 163_840,
        maxTokens: 163_840,
      },

      // ── Crof / Greg Models ──────────────────────────────────────────
      {
        id: "greg-2-ultra",
        name: "Greg 2 Ultra",
        reasoning: false,
        input: ["text"],
        cost: { input: 3.0, output: 10.0, cacheRead: 0.5, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-2-super",
        name: "Greg 2 Super",
        reasoning: false,
        input: ["text"],
        cost: { input: 1.5, output: 5.0, cacheRead: 0.25, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-1-mini",
        name: "Greg 1 Mini",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.07, output: 0.15, cacheRead: 0.01, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-rp",
        name: "Greg (Roleplay)",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },

      // ── Xiaomi ──────────────────────────────────────────────────────
      {
        id: "mimo-v2.5-pro",
        name: "Xiaomi MiMo V2.5 Pro",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.4, output: 0.8, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },

      // ── Z.ai (GLM) Models ──────────────────────────────────────────
      {
        id: "glm-5.2",
        name: "Z.ai GLM 5.2",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.5, output: 2.2, cacheRead: 0.08, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "glm-5.1",
        name: "Z.ai GLM 5.1",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.45, output: 2.15, cacheRead: 0.08, cacheWrite: 0 },
        contextWindow: 202_752,
        maxTokens: 202_752,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "glm-5",
        name: "Z.ai GLM 5",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.48, output: 1.9, cacheRead: 0.1, cacheWrite: 0 },
        contextWindow: 202_752,
        maxTokens: 202_752,
      },
      {
        id: "glm-4.7",
        name: "Z.AI GLM 4.7",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.25, output: 1.1, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 202_752,
        maxTokens: 202_752,
      },
      {
        id: "glm-4.7-flash",
        name: "Z.AI GLM 4.7 Flash",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.04, output: 0.3, cacheRead: 0.008, cacheWrite: 0 },
        contextWindow: 202_752,
        maxTokens: 131_072,
      },

      // ── MoonshotAI (Kimi) Models ────────────────────────────────────
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.55, output: 2.25, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.5, output: 1.99, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.35, output: 1.7, cacheRead: 0.07, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "kimi-k2.5-lightning",
        name: "Kimi K2.5 (Lightning)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 1.0, output: 3.0, cacheRead: 0.2, cacheWrite: 0 },
        contextWindow: 131_072,
        maxTokens: 32_768,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },

      // ── Google ──────────────────────────────────────────────────────
      {
        id: "gemma-4-31b-it",
        name: "Gemma 4 31B",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },

      // ── MiniMax ─────────────────────────────────────────────────────
      {
        id: "minimax-m2.5",
        name: "MiniMax M2.5",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.11, output: 0.95, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 204_800,
        maxTokens: 131_072,
      },

      // ── Qwen Models ────────────────────────────────────────────────
      {
        id: "qwen3.6-27b",
        name: "Qwen 3.6 27B",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.2, output: 1.5, cacheRead: 0.04, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "qwen3.5-397b-a17b",
        name: "Qwen 3.5 397B A17B",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.35, output: 1.75, cacheRead: 0.07, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
      {
        id: "qwen3.5-9b",
        name: "Qwen 3.5 9B",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.04, output: 0.15, cacheRead: 0.008, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "max",
        },
        compat: { supportsReasoningEffort: true },
      },
    ],
  });
}
